services:
  db:
    image: joselfv/books-db:v1
    container_name: db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh 127.0.0.1:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - /data-volume:/data/db/
      - ./db:/docker-entrypoint-initdb.d
    env_file:
      - ./db/.env
    networks:
      - backend
    restart: always

  api:
    image: joselfv/books-api:v1
    container_name: api
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./books-node-api/env/.env.production
    environment:
      NODE_ENV: "production"
    networks:
      - backend
      - frontend

  client:
    image: joselfv/books-client:v1
    container_name: client
    depends_on:
      - api
    env_file:
      - ./books-react-app/env/.env.production
    networks:
      - frontend
    ports:
      - "8000:80"

volumes:
  data-volume:
networks:
  backend:
  frontend:
    driver: bridge
